name: GitHub Actions Samples
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  Init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ v18.15.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build project
        run: npm run build
      - name: lint code
        run: npm run lint
      - name: lint style
        run: npm run stylelint
      - name: tests
        run: npm run test